server: # ??? ?? ??
  port: 80
spring:
  profiles: # boot ???? ??
    include: oauth # ?? ??? ??
  datasource: # ?? DB ?? ??
    url: jdbc:mariadb://localhost:3306/sogong
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rootPassword
  jpa: # jpa ??
    hibernate:
      ddl-auto: update # update ?? ??? ??? ???
    properties:
      format_sql: true
      show_sql: true

  #Live Reload
  devtools:
    livereload:
      enabled: true
  servlet: # ?? ??? ??
    multipart:
      enabled: true
      location: /Users/jideok/Documents/data
      max-request-size: 30MB
      max-file-size: 10MB

com:
  gmail:
    kangjideok:
      sogong:
        upload:
          path: /Users/jideok/Documents/data

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace # sql ???? debug
    springframework:
      security: trace